feat: update debian
BREAKING CHANGE: updated from debian bullseye to debian trixie

diff --git a/image/Dockerfile b/image/Dockerfile
--- a/image/Dockerfile
+++ b/image/Dockerfile
@@ -1,8 +1,36 @@
-FROM debian:bullseye-slim
-LABEL maintainer="zodern"
+# trixie doesn't have python 2, so we copy it from bullseye
+FROM debian:bullseye-slim AS python2
 RUN apt-get update && \
-  apt-get install -y curl python python3 make g++ bzip2 ca-certificates --no-install-recommends && \
+  apt-get install -y python2.7 libpython2.7 libssl1.1 --no-install-recommends && \
   rm -rf /var/lib/apt/lists/*
+
+FROM debian:trixie-slim
+LABEL maintainer="zodern"
+
+# libnsl2 needed for python 2
+RUN apt-get update && \
+  apt-get install -y curl python3 make g++ bzip2 ca-certificates libnsl2 --no-install-recommends && \
+  rm -rf /var/lib/apt/lists/*
+
+# Copy python 2 and make sure nothing is missing
+COPY --from=python2 /usr/bin/python2.7 /usr/bin/python2.7
+COPY --from=python2 /usr/lib/python2.7 /usr/lib/python2.7
+COPY --from=python2 /usr/lib/*-linux-gnu/libpython2.7.so.1.0 /usr/local/lib/
+COPY --from=python2 /usr/lib/*-linux-gnu/libssl.so.1.1 /usr/local/lib/
+COPY --from=python2 /usr/lib/*-linux-gnu/libcrypto.so.1.1 /usr/local/lib/
+COPY --from=python2 /usr/lib/*-linux-gnu/libffi.so.7.* /usr/local/lib/
+RUN ldconfig && \
+  set -e && \
+  for module in /usr/lib/python2.7/lib-dynload/*.so; do \
+    if ldd "$module" | grep -q 'not found'; then \
+      echo "Missing dependency for $module"; \
+      ldd "$module"; \
+      exit 1; \
+    fi; \
+  done && \
+  python2.7 -c 'import ssl, hashlib, ctypes, bz2, readline, sqlite3, zlib, nis' && \
+  ln -s /usr/bin/python2.7 /usr/bin/python2 && \
+  ln -s /usr/bin/python2.7 /usr/bin/python
 
 RUN useradd --create-home --shell /bin/bash --uid 1000 --user-group app
 
